version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ziyara-postgres
    environment:
      POSTGRES_DB: ziyara_db
      POSTGRES_USER: ziyara_user
      POSTGRES_PASSWORD: ziyara_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ziyara-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ziyara_user -d ziyara_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ziyara-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ziyara-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ziyara-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ziyara.ma
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - ziyara-network
    profiles:
      - tools

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ziyara-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - ziyara-network
    profiles:
      - tools

volumes:
  postgres_data:
  redis_data:

networks:
  ziyara-network:
    driver: bridge