spring:
  application:
    name: ziyara-backend

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/ziyara_db
    username: ziyara_user
    password: ziyara_pass
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  # JPA Configuration - AUTO SCHEMA GENERATION FOR FAST DEVELOPMENT
  jpa:
    hibernate:
      ddl-auto: update  # Changed from 'validate' to 'update' for auto schema
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 25
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    open-in-view: false

  # Liquibase - DISABLED for fast development
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false

  # Cache - using simple cache instead of Redis
  cache:
    type: simple

  # Disable Redis
  data:
    redis:
      repositories:
        enabled: false

  # DevTools
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true

# Application specific properties
app:
  cors:
    allowed-origins:
      - http://localhost:4200
      - http://localhost:3000
      - http://127.0.0.1:4200
      - http://127.0.0.1:3000

  file-upload:
    max-size: 10485760 # 10MB
    allowed-extensions: jpg,jpeg,png,gif,webp
    upload-dir: ./uploads

  pagination:
    default-page-size: 20
    max-page-size: 100

  recommendation:
    cache-ttl: 3600 # 1 hour
    max-results: 20
    default-radius-km: 50

  data:
    seed-on-startup: true

# Logging Configuration
logging:
  level:
    root: INFO
    ma.enset.ziyara: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"